### ISSUE TITLE
Viewing Results

### ISSUE THREAD

**Issue by hurtz** [GoogleCloudPlatform/PerfKitExplorer#105]
I've got PerfKitExplorer deployed, but I'm lost on how I go about taking PerfKit data in .json format and somehow upload it so I can examine results.

My goal is to have a place I can view data I've compiled from several different runs on my own servers, plus different instances in GCE and AWS. Seems like I've got all the right pieces, I just need a little help with the next step to start visualizing the data.

Apologies if this isn't the right place to ask.. I'm new to GitHib.

**Comment by voellm** [comment]
We use a sister project called PerfKitBenchmaker at Google to view the
data.  In CY2 we hope to make it super easy by publishing a dashboard for
every benchmark in PKB.  Right now we dont do that thought once you know
the basics it is easy.

JoeMu@google.com may be able to get you started.

On Tue, Apr 21, 2015 at 11:30 AM, hurtz <notifications@github.com> wrote:

> I've got PerfKitExplorer deployed, but I'm lost on how I go about taking
> PerfKit data in .json format and somehow upload it so I can examine results.
>
> My goal is to have a place I can view data I've compiled from several
> different runs on my own servers, plus different instances in GCE and AWS.
> Seems like I've got all the right pieces, I just need a little help with
> the next step to start visualizing the data.
>
> Apologies if this isn't the right place to ask.. I'm new to GitHib.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitExplorer/issues/105>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by hurtz** [comment]
Yes that's exactly what I'm trying to do - visualize the data that PerfKitBenchmarker produces.

You reference CY2, is that an upcoming release?

Has anyone written up some instructions for how to manually import the data into PerfKitExplorer?

**Comment by cmccoy** [comment]
You can import the data with the `bq` command-line tool, for example:

```
bq --project_id=<PROJECT_ID> load \
  --source_format=NEWLINE_DELIMITED_JSON \
  samples_mart.results \
  <PATH_TO_JSON_FROM_PERFKITBENCHMARKER>
```

This will be automated by PerfKitBenchmarker if you provide `--bq_project` and `--bigquery_table` flags.

This assumes a table named `results` exists within the `samples_mart` dataset.  Schema for that table can be found here:
https://github.com/GoogleCloudPlatform/PerfKitExplorer/blob/master/data/samples_mart/results_table_schema.json

**Comment by jmuharsky** [comment]
To be clear, you don't upload data to "PerfKit Explorer".  You upload it to BigQuery (a scalable data and analytical store), and PerfKit Explorer is designed to execute BigQuery SQL queries.

Over the coming quarter(s), we'll be releasing more features that give you more, easier ways to collect small and large amounts of data into BigQuery or other relevant data sources.

**Comment by hurtz** [comment]
Can I ask another dumb question?

I fumbled around enough that I was able to create a very ugly looking report using the SQL builder in PerfKitExplorer. Turned it into a chart. Also I made PerfKit send its output directly to a table, so I'm making progress.

But why would I fumble around with PerfKitExplorer with I can use something like the BigQuery / Google Sheets plugin? I'm struggling to make it work (keeps complaining the API isn't enabled for my project even though it is) but seems like its a better place to look at the data. What is it about PerfKitExplorer that makes it better suited to look at my performance data?

Thanks,
Jason

**Comment by voellm** [comment]
+Joe

Sheets is cool and may solve your need.  The Dashboard is meant to be easy
to create charts, pivots, etc and share them with your team.  They are
pretty fast and powerful.  Work really well for groups of people.

What is a bummer is it sounds like some issues are working against you
and/or the learning curve could be better.

I'm sure Joe will be happy to dig into the auth issues and help you out.
Perhaps a short 10minute Google Hangout would help?


On Fri, Apr 24, 2015 at 2:06 PM, hurtz <notifications@github.com> wrote:

> Can I ask another dumb question?
>
> I fumbled around enough that I was able to create a very ugly looking
> report using the SQL builder in PerfKitExplorer. Turned it into a chart.
> Also I made PerfKit send its output directly to a table, so I'm making
> progress.
>
> But why would I fumble around with PerfKitExplorer with I can use
> something like the BigQuery / Google Sheets plugin? I'm struggling to make
> it work (keeps complaining the API isn't enabled for my project even though
> it is) but seems like its a better place to look at the data. What is it
> about PerfKitExplorer that makes it better suited to look at my performance
> data?
>
> Thanks,
> Jason
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitExplorer/issues/105#issuecomment-96065314>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by hurtz** [comment]
I think I've got the hang of it now. I've created some nice looking dashboards with just the data I need to see.

One last question, when I pass --bq_project and --bigquery_table into pkb.py and try to directly send my results to my bigquery tables it hangs in a loop because it doesn't know the schema for my table. I'm pre-building my tables with 'bq mk perfkit_data.instance_size'. Do I need to initialize my table with a schema when I create it, and if so, how might I do that? bq mk perfkit_data.instance_size --schema /path/to/schema.json doesn't seem to work?

**Comment by voellm** [comment]
Glad to hear it.

In terms of the schema ... yes you need to have the columns defined.

Here's what we use at Google.  Some fields PKB wont publish so think of
this as a superset:
Schema
testSTRINGNULLABLE
Describe this field...
targetSTRINGNULLABLE
Describe this field...
officialBOOLEANNULLABLE
Describe this field...
product_nameSTRINGNULLABLE
Describe this field...
product_versionSTRINGNULLABLE
Describe this field...
product_envSTRINGNULLABLE
Describe this field...
product_branch_clSTRINGNULLABLE
Describe this field...
product_cherrypick_clsSTRINGNULLABLE
Describe this field...
test_versionSTRINGNULLABLE
Describe this field...
ownerSTRINGNULLABLE
Describe this field...
log_uriSTRINGNULLABLE
Describe this field...
run_uriSTRINGNULLABLE
Describe this field...
labelsSTRINGNULLABLE
Describe this field...
metricSTRINGNULLABLE
Describe this field...
valueFLOATNULLABLE
Describe this field...
unitSTRINGNULLABLE
Describe this field...
timestampFLOATNULLABLE
Describe this field...
metric_uriSTRINGNULLABLE
Describe this field...
sample_uriSTRINGNULLABLE
Describe this field...

On Thu, Apr 30, 2015 at 11:40 AM, hurtz <notifications@github.com> wrote:

> I think I've got the hang of it now. I've created some nice looking
> dashboards with just the data I need to see.
>
> One last question, when I pass --bq_project and --bigquery_table into
> pkb.py and try to directly send my results to my bigquery tables it hangs
> in a loop because it doesn't know the schema for my table. I'm pre-building
> my tables with 'bq mk perfkit_data.instance_size'. Do I need to initialize
> my table with a schema when I create it, and if so, how might I do that? bq
> mk perfkit_data.instance_size --schema /path/to/schema.json doesn't seem to
> work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitExplorer/issues/105#issuecomment-97913450>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by jmuharsky** [comment]
Pinging on this issue.  @hurtz, are you still having issues?

**Comment by hurtz** [comment]
Hi there, I've been able to successfully import and build charts for my
data. No issues here. Thanks for the assistance.
