### ISSUE TITLE
Private link in explorer.html

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitExplorer#2]
[this link](https://github.com/GoogleCloudPlatform/PerfKitExplorer/blob/79aba4b37b6b16e50eebd900563e4acc6cfa24d9/server/perfkit/explorer/handlers/templates/explorer.html#L80) can't be viewed outside of the corporate network.

**Comment by jmuharsky** [comment]
Closing as we are public now and the link should work for everyone.  The issue to public more documentation remains.
