### ISSUE TITLE
npm install failed with error:ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by qiwzhang** [GoogleCloudPlatform/PerfKitExplorer#203]
This is installed to Ubuntu 

npm install
npm WARN peerDependencies The peer dependency karma@>=0.13 included from karma-closure will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.2
 

npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-closure@0.1.1 wants karma@>=0.13
npm ERR! peerinvalid Peer karma-jasmine-html-reporter@0.1.8 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine-matchers@2.0.0-beta2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-nested-reporter@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-ng-html2js-preprocessor@0.1.2 wants karma@>=0.9

**Comment by jmuharsky** [comment]
There is a PR forthcoming to rev the version of karma.  In the meantime,
you'll need to follow the instructions below to update your dependencies.

https://github.com/GoogleCloudPlatform/PerfKitExplorer/wiki/Running-Tests

Short version:
npm install --save-dev \
    karma karma-jasmine karma-closure karma-chrome-launcher \
    karma-jasmine-html-reporter karma-ng-html2js-preprocessor

Joe

**Comment by jmuharsky** [comment]
This issue was resolved in PR #204.
