### ISSUE TITLE
Viewing Dashboard in read-only mode?

### ISSUE THREAD

**Issue by jntkflow** [GoogleCloudPlatform/PerfKitExplorer#253]
Hi, I have a dashboard that's worth sharing now, but I can't seem to find a way to share it in a way that prevents others from messing with my content. A nudge in the right direction would be greatly appreciated.

**Comment by jmuharsky** [comment]
Unless the user in question is an administrator or owner of your dashboard, they won't be able to save the changes.  In addition, you can use the Server config (if you have your own server) to restrict non-admin users from running "custom queries" (those that deviate from the saved version).

**Comment by jmuharsky** [comment]
That said, we're planning a feature in Q2 to provide an explicit Edit/View mode that will make this transition less "in your face" for new users.

**Comment by jntkflow** [comment]
Cool, good to know. Thanks!
