### ISSUE TITLE
Installation for other platforms

### ISSUE THREAD

**Issue by akrzos** [GoogleCloudPlatform/PerfKitExplorer#94]
It is mentioned that PerfKitExplorer is [extensible](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/129).  Are there instructions on how to use a different backend than big query such as MySQL and how to deploy the explorer on other platforms?

**Comment by voellm** [comment]
The model is around extending the Widget.  The Widget defines the tools
bars and backend queries.  Widgets are visually part of containers (rows).

Joe/Ivan can help you here.  Personally I've love to see a MySQL backend.

What did you have in mind?

On Fri, Feb 27, 2015 at 7:10 AM, Alex Krzos <notifications@github.com>
wrote:

> It is mentioned that PerfKitExplorer is extensible [here].(
> GoogleCloudPlatform/PerfKitBenchmarker#129
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/129>)
> Are there instructions to include how to use a different backend than bq
> and how to
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitExplorer/issues/94>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by akrzos** [comment]
I would like to deploy the PerfKitExplorer local to my machine that I am benchmarking and to be able to view the results offline.  Ideally, I could deploy the Explorer w/ MySQL on my local machine or a local VM but the instructions only discuss deploying it on Google App Engine thus far.

**Comment by jmuharsky** [comment]
I see what you're looking for, Alex.  Thanks for the clarification!  Of all
the things Explorer is coupled to, App Engine is probably the most
significant -- a non-GAE solution would require an appropriate
implementation of the /dashboard handlers and storage (currently in GAE
DataStore) and the /data handlers (wrapper to execute SQL on BigQuery).

That said, you can use dev_appserver.py to run a local copy of GAE for
testing/debugging purposes, and that may light up your scenario.  You can
read more about the local/dev app server here:

https://cloud.google.com/appengine/docs/python/tools/devserver

Hope this helps.

**Comment by voellm** [comment]
if you use the PerfKitBenchmarker (different repo) it has a local HTML
side-by-side comparison tool here -
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/master/tools/side-by-side



On Fri, Feb 27, 2015 at 8:15 AM, jmuharsky <notifications@github.com> wrote:

> I see what you're looking for, Alex. Thanks for the clarification! Of all
> the things Explorer is coupled to, App Engine is probably the most
> significant -- a non-GAE solution would require an appropriate
> implementation of the /dashboard handlers and storage (currently in GAE
> DataStore) and the /data handlers (wrapper to execute SQL on BigQuery).
>
> That said, you can use dev_appserver.py to run a local copy of GAE for
> testing/debugging purposes, and that may light up your scenario. You can
> read more about the local/dev app server here:
>
> https://cloud.google.com/appengine/docs/python/tools/devserver
>
> Hope this helps.
>
> On Fri, Feb 27, 2015 at 8:03 AM, Alex Krzos <notifications@github.com>
> wrote:
>
> > I would like to deploy the PerfKitExplorer local to my machine that I am
> > benchmarking and to be able to view the results offline. Ideally, I could
> > deploy the Explorer w/ MySQL on my local machine or a local VM but the
> > instructions only discuss deploying it on Google App Engine thus far.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/GoogleCloudPlatform/PerfKitExplorer/issues/94#issuecomment-76418340
> >
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitExplorer/issues/94#issuecomment-76420557>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by milkotodorov** [comment]
One thing is not clear to me: even if you run a local copy of the GAE, how about the BigQuery DB? This you cannot run locally? Which means that you that you must store the data in a cloud machine from google, or?

**Comment by jmuharsky** [comment]
BigQuery is a cloud-only datastore, and is presently the only supported datasource for PerfKit Explorer.  We are working this and next quarter to include additional datasources, and MySQL is a popular candidate to support.

**Comment by milkotodorov** [comment]
I see - thanks. Does this means that by March 2016 there will be MySQL support?

**Comment by jmuharsky** [comment]
I would say that's the general goal, and we're moving strongly in that direction, but we haven't released an official timetable for the feature.
