### ISSUE TITLE
Step 4 of installation-How Choose "Python & PHP" from the languages options

### ISSUE THREAD

**Issue by elham1296** [GoogleCloudPlatform/PerfKitExplorer#96]
Hi,
I have a question.
in step 4 of installation after running : curl https://sdk.cloud.google.com | bash,  the guideline says that we have to  Choose "Python & PHP" from the languages options. But I do not know how I can change language. during runnig thiss command it does not ask me about choosing language. Please help me. 
Thanks,

**Comment by jmuharsky** [comment]
The latest release of the Cloud SDK no longer asks this question.  Please ignore, and I'll update the docs shortly.

**Comment by jmuharsky** [comment]
I've got a pull request up for this, and will merge after some verification tomorrow.
https://github.com/GoogleCloudPlatform/PerfKitExplorer/pull/97
