### ISSUE TITLE
a question about modifying config/data_source_config.json file

### ISSUE THREAD

**Issue by elham1296** [GoogleCloudPlatform/PerfKitExplorer#98]
Hi,
I have 2 questions about installing PerfKitExplorer
in the "Compile and Deploy PerfKit Explorer", in the third part:"Modify the config/data_source_config.json"
1- how I could find analytics-key of my project
2- it needs to update PROD part or testing part of the data_source_config.json, or both of them 
Please help me.
Thanks

**Comment by jmuharsky** [comment]
This doc should be updated -- it isn't actually required anymore for running Explorer, just for executing tests.  Explorer as of r21 is driven by a server-side config (click the gear icon in the top right and "Edit Config" to change the relevant settings.

As far as the Analytics Key goes, if you have a Google Analytics account, you can track explorer page views (with little detail) by entering your key here.  If left empty, has no effect.

**Comment by elham1296** [comment]
Thanks
